# Configuration file for ASR-project
DATA_FEATHER = "<PATH-TO-FEATHER-FILE>.feather"
ROOT_DIR = "<ROOT_DIR>"
VOCABULARY_DIR = "<VOCABULARY_DIR"
MAX_SEQUENCE_LENGTH = 338
VALIDATION_SPLIT = 0.2
RANDOM_SEED = 42
SHUFFLE_SUBSET = True
SHUFFLE_DATASET = True
BATCH_SIZE = 64
LEARNING_RATE = 0.0003
EPOCHS = 100
NUM_WORKERS = 4
DEVICE = "cuda"
